In [4]:
import numpy as np
import random
import  copy

In [5]:
def Qpasqal(matrix , number):
    res = copy.deepcopy(matrix)
    N=res.shape[0]
    for i in range(N):
        res[i][i] =0
    # 대각 성분 0으로 만들기
    for i in range(N):
        for j in range(i+1, N):
            res[i][j] = res[i][j] +(matrix[i][i]+matrix[j][j])/((number-1)*2)
            res[j][i] = res[j][i] +(matrix[i][i]+matrix[j][j])/((number-1)*2)

    minEntity = 2000-000-000
    for i in range(N):
        for j in range(i + 1, N):
            if( res[i][j] < minEntity):
                minEntity = res[i][j]

    if minEntity <= 0:
        addValue = abs(minEntity) + 0.1
        for i in range(N):
            for j in range(i + 1, N):
                res[i][j] += addValue
                res[j][i] += addValue
        for i in range(N):
            res[i][i] = -addValue * (number - 1)

    # 맞는지 확인
    cntTrue =0
    for k in range(100):
        x =[0]*N
        sample = random.sample([i for i in range(N)],number)
        for i in sample:
            x[i] = 1
        answer = x@matrix@x
        value = x@res@x
        assert abs(answer- value) <=0.0001
        cntTrue += 1
    print("success rate : ",cntTrue/100)
    return res

In [6]:
def QpasqalOptimized(matrix, number):
    res = copy.deepcopy(matrix)
    N = res.shape[0]
    for i in range(N):
        res[i][i] = 0
    # 대각 성분 0으로 만들기
    for i in range(N):
        for j in range(i + 1, N):
            res[i][j] = res[i][j] + (matrix[i][i] + matrix[j][j]) / ((number - 1) * 2)
            res[j][i] = res[j][i] + (matrix[i][i] + matrix[j][j]) / ((number - 1) * 2)

    minEntity = 2000-000-000
    for i in range(N):
        for j in range(i + 1, N):
            if res[i][j] < minEntity:
                minEntity = res[i][j]
    if minEntity <= 0:
        addValue = abs(minEntity) + 0.1
        for i in range(N):
            for j in range(i + 1, N):
                res[i][j] += addValue
                res[j][i] += addValue
        for i in range(N):
            res[i][i] = -addValue * (number - 1)

    elif minEntity >0.1:
        addValue = minEntity-0.1
        for i in range(N):
            for j in range(i + 1, N):
                res[i][j] -= addValue
                res[j][i] -= addValue
        for i in range(N):
            res[i][i] = addValue * (number - 1)

    # 맞는지 확인
    cntTrue = 0
    for k in range(100):
        x = [0] * N
        sample = random.sample([i for i in range(N)], number)
        for i in sample:
            x[i] = 1
        answer = x @ matrix @ x
        value = x @ res @ x
        assert abs(answer - value) <= 0.0001
        cntTrue += 1
    print("success rate : ", cntTrue / 100)
    return res

In [7]:

matrix = np.random.randn(5, 5)+10
matrix = (matrix + matrix.T) / 2
matrix

array([[ 9.93687922, 10.3724776 ,  9.86100585,  9.84282459, 11.33084513],
       [10.3724776 , 10.921141  , 10.03440369,  9.13685052, 10.35574689],
       [ 9.86100585, 10.03440369,  9.06373418, 10.45333402, 10.89230919],
       [ 9.84282459,  9.13685052, 10.45333402, 11.38794288, 10.61043437],
       [11.33084513, 10.35574689, 10.89230919, 10.61043437, 10.21116793]])

In [8]:
Qpasqal(matrix ,3)


success rate :  1.0


array([[ 0.        , 15.58698265, 14.61115921, 15.17403012, 16.36785691],
       [15.58698265,  0.        , 15.03062249, 14.71412149, 15.63882413],
       [14.61115921, 15.03062249,  0.        , 15.56625328, 15.71103472],
       [15.17403012, 14.71412149, 15.56625328,  0.        , 16.01021208],
       [16.36785691, 15.63882413, 15.71103472, 16.01021208,  0.        ]])

In [9]:
QpasqalOptimized(matrix ,3)

success rate :  1.0


array([[29.02231841,  1.07582345,  0.1       ,  0.66287091,  1.85669771],
       [ 1.07582345, 29.02231841,  0.51946328,  0.20296229,  1.12766492],
       [ 0.1       ,  0.51946328, 29.02231841,  1.05509408,  1.19987551],
       [ 0.66287091,  0.20296229,  1.05509408, 29.02231841,  1.49905287],
       [ 1.85669771,  1.12766492,  1.19987551,  1.49905287, 29.02231841]])