In [5]:
import numpy as np
import random
import  copy

In [50]:
def Qpasqal(matrix , number):
    res = copy.deepcopy(matrix)
    N=res.shape[0]
    for i in range(N):
        res[i][i] =0
    # 대각 성분 0으로 만들기
    for i in range(N):
        for j in range(i+1, N):
            res[i][j] = res[i][j] +(matrix[i][i]+matrix[j][j])/((number-1)*2)
            res[j][i] = res[j][i] +(matrix[i][i]+matrix[j][j])/((number-1)*2)

    minEntity = 2000-000-000
    for i in range(N):
        for j in range(i + 1, N):
            if( res[i][j] < minEntity):
                minEntity = res[i][j]

    if minEntity <= 0:
        addValue = abs(minEntity) + 0.1
        for i in range(N):
            for j in range(i + 1, N):
                res[i][j] += addValue
                res[j][i] += addValue
        for i in range(N):
            res[i][i] = -addValue * (number - 1)

    # 맞는지 확인
    cntTrue =0
    for k in range(100):
        x =[0]*N
        sample = random.sample([i for i in range(N)],number)
        for i in sample:
            x[i] = 1
        answer = x@matrix@x
        value = x@res@x
        assert abs(answer- value) <=0.0001
        cntTrue += 1
    print("success rate : ",cntTrue/100)
    return res

In [51]:
def QpasqalOptimized(matrix, number):
    res = copy.deepcopy(matrix)
    N = res.shape[0]
    for i in range(N):
        res[i][i] = 0
    # 대각 성분 0으로 만들기
    for i in range(N):
        for j in range(i + 1, N):
            res[i][j] = res[i][j] + (matrix[i][i] + matrix[j][j]) / ((number - 1) * 2)
            res[j][i] = res[j][i] + (matrix[i][i] + matrix[j][j]) / ((number - 1) * 2)

    minEntity = 2000-000-000
    for i in range(N):
        for j in range(i + 1, N):
            if res[i][j] < minEntity:
                minEntity = res[i][j]
    if minEntity <= 0:
        addValue = abs(minEntity) + 0.1
        for i in range(N):
            for j in range(i + 1, N):
                res[i][j] += addValue
                res[j][i] += addValue
        for i in range(N):
            res[i][i] = -addValue * (number - 1)

    elif minEntity >0.1:
        addValue = minEntity-0.1
        for i in range(N):
            for j in range(i + 1, N):
                res[i][j] -= addValue
                res[j][i] -= addValue
        for i in range(N):
            res[i][i] = addValue * (number - 1)

    # 맞는지 확인
    cntTrue = 0
    for k in range(100):
        x = [0] * N
        sample = random.sample([i for i in range(N)], number)
        for i in sample:
            x[i] = 1
        answer = x @ matrix @ x
        value = x @ res @ x
        assert abs(answer - value) <= 0.0001
        cntTrue += 1
    print("success rate : ", cntTrue / 100)
    return res

In [52]:

matrix = np.random.randn(5, 5)+10
matrix = (matrix + matrix.T) / 2
matrix

array([[ 9.45270134,  9.83648322, 11.75426791,  9.3058398 , 10.03894215],
       [ 9.83648322, 10.64262481, 10.34132322,  9.70234332, 10.9410921 ],
       [11.75426791, 10.34132322, 10.71179952,  9.8978519 , 10.00228123],
       [ 9.3058398 ,  9.70234332,  9.8978519 , 10.64824763,  9.64788756],
       [10.03894215, 10.9410921 , 10.00228123,  9.64788756,  9.57421913]])

In [53]:
Qpasqal(matrix ,3)


success rate :  1.0


array([[ 0.        , 14.86031475, 16.79539313, 14.33107704, 14.79567227],
       [14.86031475,  0.        , 15.6799293 , 15.02506143, 15.99530308],
       [16.79539313, 15.6799293 ,  0.        , 15.23786368, 15.07378589],
       [14.33107704, 15.02506143, 15.23786368,  0.        , 14.70350425],
       [14.79567227, 15.99530308, 15.07378589, 14.70350425,  0.        ]])

In [54]:
QpasqalOptimized(matrix ,3)

success rate :  1.0


array([[28.46215408,  0.62923772,  2.56431609,  0.1       ,  0.56459523],
       [ 0.62923772, 28.46215408,  1.44885226,  0.7939844 ,  1.76422605],
       [ 2.56431609,  1.44885226, 28.46215408,  1.00678665,  0.84270886],
       [ 0.1       ,  0.7939844 ,  1.00678665, 28.46215408,  0.47242721],
       [ 0.56459523,  1.76422605,  0.84270886,  0.47242721, 28.46215408]])