In [5]:
import numpy as np
import random
import  copy

In [14]:

def Qpasqal(matrix , number):
  res = copy.deepcopy(matrix)
  N=res.shape[0]
  for i in range(N):
    res[i][i] =0
  # 대각 성분 0으로 만들기
  for i in range(N):
    for j in range(i+1, N):
      res[i][j] = res[i][j] +(matrix[i][i]+matrix[j][j])/((number-1)*2)
      res[j][i] = res[j][i] +(matrix[i][i]+matrix[j][j])/((number-1)*2)

  minEntity = 0
  for i in range(N):
    for j in range(i+1, N):
      if( res[i][j] < minEntity):
        minEntity = res[i][j]

  if minEntity <= 0:
    addValue = abs(minEntity)+0.1
    for i in range(N):
      for j in range(i+1, N):
        res[i][j] += addValue
        res[j][i] += addValue
    for i in range(N):
      res[i][i] = -addValue*(number-1)


  # 맞는지 확인
  cntTrue =0
  for k in range(100):
    x =[0]*N
    sample = random.sample([i for i in range(N)],number)
    for i in sample:
        x[i] = 1
    answer = x@matrix@x
    value = x@res@x
    assert abs(answer- value) <=0.0001
    cntTrue += 1
  print("success rate : ",cntTrue/100)
  return res

In [ ]:
def QpasqalOptimized(matrix, number):
    res = copy.deepcopy(matrix)
    N = res.shape[0]
    for i in range(N):
        res[i][i] = 0
    # 대각 성분 0으로 만들기
    for i in range(N):
        for j in range(i + 1, N):
            res[i][j] = res[i][j] + (matrix[i][i] + matrix[j][j]) / ((number - 1) * 2)
            res[j][i] = res[j][i] + (matrix[i][i] + matrix[j][j]) / ((number - 1) * 2)

    minEntity = 2000-000-000
    for i in range(N):
        for j in range(i + 1, N):
            if res[i][j] < minEntity:
                minEntity = res[i][j]

    if minEntity <= 0:
        addValue = abs(minEntity) + 0.1
        for i in range(N):
            for j in range(i + 1, N):
                res[i][j] += addValue
                res[j][i] += addValue
        for i in range(N):
            res[i][i] = -addValue * (number - 1)

    elif minEntity >0.1:
        addValue = minEntity-0.1
        for i in range(N):
            for j in range(i + 1, N):
                res[i][j] -= addValue
                res[j][i] -= addValue
        for i in range(N):
            res[i][i] = addValue * (number - 1)

    # 맞는지 확인
    cntTrue = 0
    for k in range(100):
        x = [0] * N
        sample = random.sample([i for i in range(N)], number)
        for i in sample:
            x[i] = 1
        answer = x @ matrix @ x
        value = x @ res @ x
        assert abs(answer - value) <= 0.0001
        cntTrue += 1
    print("success rate : ", cntTrue / 100)
    return res

In [37]:

matrix = np.random.randn(5, 5) +2
matrix = (matrix + matrix.T) / 2

matrix

array([[0.02497487, 1.70752196, 2.58143898, 1.46627054, 0.55064533],
       [1.70752196, 1.39202255, 2.11087565, 3.08122311, 0.71205789],
       [2.58143898, 2.11087565, 1.25492943, 2.66664455, 2.68928001],
       [1.46627054, 3.08122311, 2.66664455, 2.29334505, 2.19764996],
       [0.55064533, 0.71205789, 2.68928001, 2.19764996, 3.25639261]])

In [38]:
Qpasqal(matrix ,3)


success rate :  1.0


array([[-0.2       ,  2.16177131,  3.00141505,  2.14585052,  1.4709872 ],
       [ 2.16177131, -0.2       ,  2.87261365,  4.10256501,  1.97416168],
       [ 3.00141505,  2.87261365, -0.2       ,  3.65371317,  3.91711052],
       [ 2.14585052,  4.10256501,  3.65371317, -0.2       ,  3.68508437],
       [ 1.4709872 ,  1.97416168,  3.91711052,  3.68508437, -0.2       ]])

In [39]:
QpasqalOptimized(matrix ,3)

success rate :  1.0


array([[2.5419744 , 0.79078412, 1.63042785, 0.77486332, 0.1       ],
       [0.79078412, 2.5419744 , 1.50162645, 2.73157781, 0.60317448],
       [1.63042785, 1.50162645, 2.5419744 , 2.28272597, 2.54612332],
       [0.77486332, 2.73157781, 2.28272597, 2.5419744 , 2.31409718],
       [0.1       , 0.60317448, 2.54612332, 2.31409718, 2.5419744 ]])